### ISSUE TITLE
Feature request: align %browse magic syntax with Stata 

### ISSUE THREAD

**Issue by ideabucket** [ticoneva/pystata-kernel#12]
At the moment the `%browse` magic syntax to show the first 7 records of a dataset is:

```
*%browse 7 [varlist…] [if…]
```

The equivalent command in the Stata app is:

```stata
browse [varlist…] [if…] in 1/7
```

It would be great if the browse magic followed stata syntax for two reasons:

1. Do-files from one source could be trivially exchanged with the other;
2. Explicit specification of the start record would allow [records beyond the first 200](https://github.com/ticoneva/pystata-kernel/commit/be74a50b3110c6835e7ecea1340f0839bf882eed#diff-50e907f054190aeed1c72c8b4e8471f5ce6ea5c12e61bc2b1d7aa1fccd919ac5R89) to be viewed.

I'm happy to have a go at writing a PR for this if you're not already working on it.

**Comment by ticoneva** [comment]
I agree that aligning syntax with Stata is a good idea, but for magics I also want to maintain compatibility with `stata-kernel`. One possibility is to allow both `N` and `in`, but outputs an error when the user tries to include both.  

While we are at this topic, we could also consider using `browse` instead of `%browse` or `*%browse`. The reason is, while `browse` is a valid command in Stata GUI&mdash;it opens the data editor in browse mode&mdash;it is not valid in console mode, and by extension,  in `pystata`. There is thus no risk of overwriting any default behavior, because there is none to begin with.

**Comment by ideabucket** [comment]
One option might be to select syntax based on how the magic is invoked: 

- if invoked as `%browse`, follow `stata-kernel` syntax
- if invoked as `*%browse`, follow Stata-aligned syntax (since `stata-kernel` wouldn't recognise that anyway and so backwards-compatibility is not required)

I love the idea of taking over `browse`, but it feels like it would be a lot of work: what happens if there's a `browse` command somewhere in the middle of a multi-line cell? If the kernel only picks up `browse` as the first/only line of a cell, you have a situation where the exact same command produces different behaviour depending on where it is in the code; but to get consistent behaviour you'd have to essentially write a Stata language parser so you could pick out the commands that need to be taken over by the kernel, which is like the issue from #4 but worse.

**Comment by ticoneva** [comment]
Release `0.2.3` adds support for `[in]`. [Syntax](https://www.stata.com/help.cgi?in) is the same as in Stata. Please check if it is working as intended.

**Comment by ideabucket** [comment]
I've submitted a PR with a small behind-the-scenes update but from a functional point of view the stata-esque syntax seems to work properly.

One UI issue, though: the row numbering in the browse table is always 0…N. This is a problem in two ways:

- Stata's observation index starts from 1, so if you do `browse in 1/10` you will get a table numbered from 0–9.
- If your starting observation isn't 1, pandas still numbers the table from 0. So if you do `browse in 15/20` the row numbers will be 0–5. 

Ideally the row numbers should reflect the observation's index in Stata. Failing that, it is probably better not to display them at all.

**Comment by ticoneva** [comment]
We could generate a new Stata variable that equals to `_n` everytime `*%browse` is called and display that instead of `pandas`' built-in index. What do you think?

**Comment by ideabucket** [comment]
Row numbers implemented as of #14.

**Comment by gaksaray** [comment]
I appreciate the `*% browse [in]` implementation. However, as of version 0.3.1, I come across some issues.

`*% browse [in]` by itself doesn't finalize running and gets stuck on `[*]`:

<img width="688" alt="1" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/91875ca8-8905-4c74-868c-ac332fbaa7fc">

One would need to add an `N` argument (any number) to it for it to work:

<img width="942" alt="2" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/14dd9c92-63fb-4fa7-88bd-ded6eb46c95b">

... or a valid `[if]` expression:

<img width="939" alt="if" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/03e3ea27-45fb-4752-b657-47abf37734bc">

Another issue is that when `*% browse` produces an error, an extraneous variable is permanently created:

<img width="941" alt="3" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/f9b94d29-d131-431b-a1fa-fcaee98bee13">

In this example, `[2]` produces an out-of-range error, and `[3]` shows that a variable named `__000000` is added to the dataset, which is not the expected behavior.

**Comment by ticoneva** [comment]
Fixed the issue of `*%browse` getting stuck when using `in` alone in version `0.3.2`.

Leaving behind temporary variables after a crash is the default behavior of Stata, and I do not think it is imperative to delete them through the kernel.

**Comment by gaksaray** [comment]
I have found another issue. When negative numbers are used in the `in` range identifier, `*%browse` behaves inconsistently with its native Stata counterpart.

In Stata, `browse in -1` shows the last observation:

<img width="526" alt="Screenshot 2024-02-29 at 09 12 56" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/73bef01e-3702-4319-8a6f-7cf4cec37093">

Whereas in `pystata-kernel`, `*%browse in -1` shows the whole dataset:

<img width="896" alt="Screenshot 2024-02-29 at 09 10 59" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/f70d4acb-746c-4ed5-a916-231ad954f320">

In Stata, `browse in -2/l` shows the last two observations:

<img width="471" alt="Screenshot 2024-02-29 at 09 13 10" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/a6ad8d05-6344-42c1-bd3b-ca73dd3a1608">

Whereas in `pystata-kernel`, `*%browse in -2/l` shows the last three observations appended to the whole dataset:

<img width="897" alt="Screenshot 2024-02-29 at 09 12 03" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/c576e2b2-9cae-403a-a75e-a8da97970d52">

In Stata, `browse in -1/l` shows the last observation:

<img width="446" alt="Screenshot 2024-02-29 at 09 13 20" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/b038fa9b-c932-4245-9fb0-96bd08d246b6">

Whereas in `pystata-kernel`, `*%browse in -1/l` shows the last two observations appended to the whole dataset:

<img width="874" alt="Screenshot 2024-02-29 at 09 12 23" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/bbfc7169-fa12-4a0c-b169-69da14e1fcee">

**Comment by hugetim** [comment]
These examples work in `nbstata`, somewhat to my surprise. The code is here: https://github.com/hugetim/nbstata/blob/master/nbs/07_browse.ipynb
